SELECT APP_USER.username,CATEGORY.NAME,FLASHCARD.question,FLASHCARD.answer
FROM APP_USER
   INNER JOIN
   STUDY_SET
   ON APP_USER.user_id=Study_set.owner_id
   INNER JOIN
   STUDY_SET_CARD
   ON STUDY_SET.STUDY_SET_ID=STUDY_SET_CARD.STUDY_SET_ID
   INNER JOIN
   FLASHCARD
   ON STUDY_SET_CARD.flashcard_id=FLASHCARD.Flashcard_id
   INNER JOIN
   CATEGORY
   ON FLASHCARD.CATEGORY_id=CATEGORY.category_ID
   WHERE STUDY_SET.owner_id=4;